import { Bill } from "./types";

export const BILLS: Bill[] = [
  {
    id: 1,
    code: "CA SB-567",
    title: "Rent Stabilization Act",
    source: "STATE",
    score: 9,
    date: "Apr 18",
    tag: "Tenant Protections",
    summary: "Caps annual rent increases at 5% + CPI for most residential tenants in California, with just-cause eviction protections.",
    fullText: "CA SB-567 amends the Tenant Protection Act of 2019, limiting annual rent increases to no more than 5% plus the local CPI (max 10%), expanding coverage to single-family homes and condos, and requiring landlords to provide documented just-cause for any eviction. Effective January 1, 2025.",
  },
  {
    id: 2,
    code: "CA AB-2176",
    title: "University Campus Housing Funding",
    source: "STATE",
    score: 7,
    date: "Apr 15",
    tag: "Education",
    summary: "Allocates $500M in state bonds for UC/CSU on-campus housing construction targeting low-income students.",
    fullText: "CA AB-2176 authorizes $500 million in general obligation bonds for construction of on-campus dormitories and student housing at UC and CSU campuses, prioritizing students from households below 80% AMI. Projects must break ground within 3 years of funding.",
  },
  {
    id: 3,
    code: "Federal HR-4521",
    title: "SNAP Benefits Expansion",
    source: "FEDERAL",
    score: 8,
    date: "Apr 12",
    tag: "Food Security",
    summary: "Increases SNAP monthly allotments by 15% and expands eligibility thresholds for working families.",
    fullText: "HR-4521 amends the Food and Nutrition Act to increase monthly SNAP benefit allotments by 15%, raise the gross income eligibility threshold from 130% to 165% of the federal poverty level, and eliminate asset tests for households with a member over 60 or disabled.",
  },
  {
    id: 4,
    code: "Berkeley CC",
    title: "Childcare Subsidy Program",
    source: "LOCAL",
    score: 6,
    date: "Apr 10",
    tag: "Family Support",
    summary: "City-funded childcare subsidies for Berkeley families earning under 120% AMI, up to $1,200/month.",
    fullText: "Berkeley City Council Resolution 2024-041 establishes a municipal childcare subsidy of up to $1,200/month per child for families earning below 120% of the Area Median Income. Program funded through Measure FF hotel tax revenue.",
  },
  {
    id: 5,
    code: "Federal S-1234",
    title: "Student Loan Interest Rate Cap",
    source: "FEDERAL",
    score: 7,
    date: "Apr 8",
    tag: "Student Debt",
    summary: "Caps federal student loan interest rates at 5% and allows refinancing of all existing loans at current rates.",
    fullText: "S-1234 caps interest rates on all federal student loans at 5%, retroactively applies to existing balances, and creates a one-time refinancing window. Borrowers with income under $50,000 qualify for zero-interest status.",
  },
];
